name: pomodoro_timer
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.7.0"
  flutter: 3.3.8

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  hydrated_bloc: ^10.0.0
  intl: ^0.19.0
  just_audio: ^0.9.32
  launch_at_startup: ^0.3.1
  package_info_plus: ^8.2.1
  path_provider: ^2.0.15
  process_run: ^1.2.3
  system_tray: ^2.0.3
  window_manager: ^0.4.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.3.3
  copy_with_extension_gen: ^6.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/audio/
    - assets/icon/
